language: java

env:
  global:
    secure: GpxpEvW7SY8AvUJvAMqQOdZL5BZhtBPGsBfXqwuC+vbaezL6a9wbc9eVYq7rQwUcmjB+QDZGX6qlIURDL4ZlS3caVN0iAAbaC5w1cW70Skc56UI5qZId5FdzpzqcfnDVCYLkBfp6tMY++X8+SOmBd/CLji2kKC50Qw/6HNRwqqY=

branches:
  only:
  - master

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

script: mvn clean deploy

notifications:
  email: false
